WITH RENTAL_INFO AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION, 
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7  THEN '7일 이상'
            ELSE '할인 없음' 
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT
    R.HISTORY_ID,
    ROUND(C.DAILY_FEE * R.DURATION * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM
    RENTAL_INFO R 
JOIN
    CAR_RENTAL_COMPANY_CAR C ON R.CAR_ID = C.CAR_ID
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE AND R.DURATION_TYPE = P.DURATION_TYPE
WHERE
    C.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC, R.HISTORY_ID DESC;